Repository MarcelaSerrano98/red-social-python-scrum, pull requests merged in 2025-07, with the labels that each got.

#13 Hu03 listado de usuarios
  logica/listado_de_usuarios.py
  menu/menus.py
Labels: épica: usuarios

#19 Hu06 hu07 comentar like publicacion
  logica/verPublicaciones.py
  savefiles/users.json
Labels: épica: interfaz

#24 Hu11 mensajes de error amigables
  logica/registro.py
  savefiles/users.json
Labels: épica: interfaz

#25 Hu13 visualizar perfil otros usuarios
  logica/login.py
  logica/visualizar_perfil_usuarios.py
  menu/menus.py
Labels: épica: usuarios

#28 Hu15 mejorar interfaz
  app/main.py
  logica/crearPublicaciones.py
  logica/editarMisPublicaciones.py
  logica/interactuarPublicacion.py
  logica/limpiarConsola.py
  logica/listado_de_usuarios.py
  logica/login.py
  logica/registro.py
  logica/visualizar_perfil_usuarios.py
  menu/menus.py
  savefiles/users.json
Labels: épica: interfaz

#29 Hu15 mejorar interfaz
  README.md
Labels: documentation
